Add Elastic Fleet reset script
Security-Onion-Solutions/securityonion pull request #11678
Opened 2023-11-01 20:52 UTC by defensivedepth

2023-11-01 21:03 UTC, jertel requested changes

2023-11-01 21:03 UTC, jertel commented on salt/manager/tools/sbin_jinja/so-elastic-fleet-reset
> +    INDXS=$(curl -K /opt/so/conf/kibana/curl.config -s -k -L -H "Content-Type: application/json" "https://localhost:9200/_resolve/index/${ALIAS}"  | jq -r '.aliases[].indices[]')
If Kibana fails to respond, what happens?

2023-11-01 21:03 UTC, jertel commented on salt/manager/tools/sbin_jinja/so-elastic-fleet-reset
> +            curl -K /opt/so/conf/kibana/curl.config -s -k -L -H "Content-Type: application/json" "https://localhost:9200/${INDX}" -XDELETE
Handle Kibana response error

2023-11-02 11:41 UTC, defensivedepth commented on salt/manager/tools/sbin_jinja/so-elastic-fleet-reset
> +if [ "$INPUT" != "AGREE" ] ; then exit 0; fi
Completed

2023-11-02 11:45 UTC, defensivedepth commented on salt/manager/tools/sbin_jinja/so-elastic-fleet-reset
> +salt \* cmd.run "elastic-agent uninstall -f" queue=True
It's expected that there may be errors here if Elastic Agent is not actually installed - and that's fine.

2023-11-02 14:39 UTC, jertel approved these changes

2023-11-02 15:33 UTC, merged