Update so-whiptail
Security-Onion-Solutions/securityonion pull request #4300
Opened 2021-05-26 13:55 UTC by j-bernal

Updated Zeek capitalization when prompting for the number of processes.

2021-05-26 13:58 UTC, rwwiv approved these changes

2021-05-26 13:58 UTC, TOoSmOotH approved these changes

2021-05-26 13:59 UTC, rwwiv requested changes
Needs to be to `dev` not `master`

2021-05-26 14:00 UTC, TOoSmOotH requested changes, later dismissed
send to dev

2021-05-26 14:01 UTC, rwwiv approved these changes
Changed the base branch to `dev`

2021-05-27 11:54 UTC, dougburks approved these changes

2021-05-27 11:58 UTC, merged